server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/es?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 419520
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 110.40.211.224
    port: 5672
    virtual-host: /
    username: admin
    password: 123456
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.xn2001.hotel.pojo